language:
- python
os:
- linux
python:
- '3.6'
install:
- pip install --upgrade pip
- pip install setuptools
- pip install --upgrade setuptools
- pip install coveralls
- pip install -e .
- pip list
script:
- python setup.py test
- coverage run --source="crc/crc.py" setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: AIGEEHerHVkn7wnKUe3bBIQCLXtpvQZCMHJeXbXqvH/tktoF8Ula5ZWgGwia8hVbIx9eOXJ0s2G0QL/2NmhbtITluqLZUg/wdBtgE9EFCoAKTtSthGrMyUTr/UMT5fC4zSP3YAtLixrIMSphLHQJtelDEVyILvpkTrXi88SIei7YWSGCjokAlmxHAeqK31yhw2yilsRUysXQXbCTcyI8M3re8zzpp5jyHU7PP7GLYyyIPD4WO7SKqXAmg2blbEArv178U6n6d2mq18iJdoepXhzQ4Tc8IYXtPHCJ9yWqWyxRhcyHXWIvwmd1m3AYUb9hsamwLGQF7A4iqFogCAUx73Ks2uag6MSjnVHE1IFopwNru0E3zk+lAYnb4mE9KTIVOGKrCjlAI8odFx+DTN9oLHOE7wlba8bB3OSrcFyhQIddSVPWUsekiPJVevcGfgaSxaoJfwFtD5icB1F5vjWnM+GZeoQC59RCXJPH9AIVIGYKhuJUMSbqfURkE0AWsHAyfxGzB8iDUCr/i/f4S20UuUtR0ju/vuxRDpqOBdlpYIsfzp+ex1lRUt9yDP2sLk7y4QrT2VLCJCpb6HzQB54Els3mK/xFQUH4XouxOcERM6d2SZ+9+oZzK9l5U9cGG4QiZsOw0j2f+BBV5Yr902+WheTYVu1ak5rOgNtqjzk5qDA=
  on:
    tags: true
